Add #field_text at CMS::FormBuilder
CONTEXT:

During the work dockerizing CMS for Jenkins CI tests runs, a
"Building Homepage Pages" feature test started failing.
(features/pages_form/mas_homepage_pages.feature)

Error:
undefined method `field_text' for <Cms::FormBuilder:0x0055c3e6eb8688>
Did you mean?  field_date_time (ActionView::Template::Error)
      ./app/helpers/pages_helper.rb:9:in `tag_for_identifier'

This test was sistematically failing in Docker, but running correctly
on developers machines (Macbooks).

As I use Linux as a development machine I actually had the same issue
with this test as Jenkins Docker runs.

Debugging the issue locally, I found that the main issue it comes from
the tag classes differing between Linux and Mac environments:
- Linux "tag.class" returns  ComfortableMexicanSofa::Tag::FieldText
- Mac "tag.class" returns  ComfortableMexicanSofa::Tag::FieldString

Both seems to be valid Tag classes with almost identical definitions
in our comfortable-mexican-sofa gem fork:
- https://github.com/moneyadviceservice/comfortable-mexican-sofa/tree/master/lib/comfortable_mexican_sofa/tags

WHY I TOOK THIS APPROACH:

Seems something in the local runtime makes Linux and Mac machines differ
about what tag class to use between FieldText and FieldString, but in
our CMS::FormBuilder class we only have an implementation for
FieldString tags.

Adding a FieldText implementation in CMS::FormBuilder gives use the same
behaviour independently of the running environment, while won't affect
previous codebase as we're not adding any logic switch, but covering a
further tag that wasn't covered until now.

(cherry picked from commit 8b4b6b3f216a432df6fe77f0e6fdfd2818d8ae42)